### PR TITLE
Fix Could not load file or assembly 'Mono.Cecil'

### PR DESCRIPTION
**Pull request by pengweiqhca**
Fix https://github.com/pardeike/Harmony/issues/255

`ILRepack.MSBuild.Task` don't support packing netcoreapp when use `MSBuild`, but support `dotnet build`
```
Failed to resolve System.Reflection.BindingFlags
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at ILRepacking.ILRepack.Repack()
   at ILRepack.MSBuild.Task.ILRepack.Execute()	Harmony	D:\Documents\GitHub\Harmony\Harmony\Harmony.csproj	101	

```

### CODE REVIEW

**Comment by pardeike** [comment]
Can you explain more? This PR and the #255 have very little information. For me the build works for netcoreapp. Without a complete analysis of the problem and why you think your changes solve it (and keep the existing features) I cannot accept this PR.

**Comment by pengweiqhca** [comment]
> Can you explain more? This PR and the #255 have very little information. For me the build works for netcoreapp. Without a complete analysis of the problem and why you think your changes solve it (and keep the existing features) I cannot accept this PR.

``` bash
git clone https://github.com/pengweiqhca/HarmonyDemo.git
cd HarmonyDemo
dotnet run
```
You will get a exception. Modify the `TargetFramework` to `net471`, you will not get a exception.

**Comment by 0x0ade** [comment]
I'm heading out to work in a few minutes, not at my PC for a few hours, but
my 2ct:

Just checked the nuspec in the nupkg on NuGet. The .NET Core 3.0 and 3.1
dependency sections are empty.

I'll see what I can do about this when I'm back, but I'll probably need to
publish MonoMod.Common to nuget.org, and it'll need to be made a
non-private dependency in the Harmony .csproj for .NET Core only. (Still
private for .NET Fx because it's being merged.)

**Comment by pengweiqhca** [comment]
Two ways are all right

**Comment by pengweiqhca** [comment]
Look https://github.com/pardeike/Harmony/pull/263

**Pull request closed without merging**
