### PR TITLE
Adding .NET Standard 2.1 support

### PR DESCRIPTION
**Pull request by warkenji**

### CODE REVIEW

**Comment by pardeike** [comment]
Support for .Net Standard was removed because System.Reflection.Emit was removed from Nuget and without it Harmony cannot do its job.

**Comment by warkenji** [comment]
> System.Reflection.Emit

.Net Standard 2.1 don't need it :)

**Comment by sunnamed434** [comment]
Any thoughts on adding it?

**Comment by pardeike** [comment]
Thoughts? More than the existing statements made in this thread, no nothing has changed since my last comment.

**Pull request closed without merging**
