### PR TITLE
Add convenient accessor class

### PR DESCRIPTION
**Pull request by enemyofthedawn**
Something what was proposed here: https://github.com/pardeike/Harmony/issues/20#issuecomment-311988446

Basically it's a nice looking helper(under the hood using`Traverse`) for accessing/modifying field and property values. 

Example:

```csharp
var accessor = Accessor.ForInstance(someinstance);
var fieldValue = accessor.Field<int>("_someIntField").Value;
var propertyValue = accessor.Property<int>("SomeIntProperty").Value;

var healthFieldReference = accessor.Field<int>("_health");
// Modifying values is possible too
healthFieldReference.Value = 999;

```

### CODE REVIEW

**Comment by pardeike** [comment]
Is the sole benefit of this API to allow writing
```csharp
var accessor = Accessor.ForInstance(someinstance);
var fieldValue = accessor.Field<int>("_someIntField").Value;
```
instead of
```sharp
var fieldValue = Traverse.Create(someinstance).Field("_someIntField").GetValue<int>();
```
or
```sharp
var traverse = Traverse.Create(someinstance);
var fieldValue = traverse.Field("_someIntField").GetValue<int>();
```
or
```sharp
var traverse = Traverse.Create(someinstance).Field("_someIntField");
var fieldValue = traverse.GetValue<int>();
```
I am not sure if that adds a sufficient benefit compared to the complexity to document and explain the class to end users. Too many choices can be contra productive.

What is the motivation behind your proposal?

**Comment by pardeike** [comment]
Also note, that we already have extra API like FastAccess:
https://github.com/pardeike/Harmony/blob/master/Harmony/Extras/FastAccess.cs

**Comment by fromdusktilldawn** [comment]
Under the hood it still uses `Traverse` but it's easier to write and looks cleaner. So it can be treated more like a wrapper for `Traverse`. I created it because at some point I started using `Traverse` and it was really annoying to use. I didn't notice there's something like FastAccess, but still it's not that convenient to use. Maybe it would be faster to use `FastAccess` instead of `Traverse` for this class.

Personally I think it is much better to assign values like:

`someField.Value = 1` than `someField.SetValue<int>(1)`

**Comment by pardeike** [comment]
I am not going to accept this pull request. But I am going to try to incorporate your simplified API into Traverse directly. Your class is too similar to Traverse and does not offer chaining. So by instead adding the core simplification into Traverse, we get the best of both worlds.

If we add your `Value getter/setter` to traverse we get the same result, don't we? Or am I missing something here?

**Comment by fromdusktilldawn** [comment]
And how are you going to get `T`? You can't have generic property in C#, `Traverse` class is not generic and this kind of syntax won't be possible.

**Comment by pardeike** [comment]
I understand where you are coming from. I just think keeping most of Traverse and its feature and adding your final step to it gives the same result without a whole new way to define type and field names.

So my proposal is to add
```csharp
public class Accessor<T>
{
	private Traverse traverse;

	public Accessor(Traverse traverse)
	{
		this.traverse = traverse;
	}

	public T Value
	{
		get { return traverse.GetValue<T>(); }
		set { traverse.SetValue(value); }
	}
}
```
and
```csharp
public Accessor<T> Field<T>(string name)
{
	return new Accessor<T>(Field(name));
}

public Accessor<T> Property<T>(string name, object[] index = null)
{
	return new Accessor<T>(Property(name, index));
}
```
directly to `Traverse`. Which allows to write:
```csharp
var someField = Traverse.Create(someInstance).Field<FieldType>("someField");
someField.Value = ...;
```

**Pull request closed without merging**
