### PR TITLE
Update MonoMod.Common version, support tiered compilation

### PR DESCRIPTION
**Pull request by pengweiqhca**

### CODE REVIEW

**Comment by pardeike** [comment]
Thanks for making the dependency version into one value

**Comment by 0x0ade** [comment]
Simply updating MonoMod.Common isn't enough for Harmony to fully support tiered compilation. Harmony needs to implement a handler for [the new `OnMethodCompiled` event](https://github.com/MonoMod/MonoMod.Common/blob/74a4f28417c9e7c61bba4c0cf349f09daf079ec4/RuntimeDetour/IDetourRuntimePlatform.cs#L21) - bumping the version number and not handling that event is pretty much meaningless.

**Comment by pardeike** [comment]
Working on it. Just need to figure out how to use OnMethodCompile with my internal state. I talked to the guy who implemented it not so long ago but already forgot all the details XD

**Comment by pardeike** [comment]
[This commit](https://github.com/pardeike/Harmony/commit/718b979a212e4edab9e3d2e99c67fd5f6739fc0d) implements an experimental version of the OnMethodCompile event. @0x0ade can you have a quick look at the change so I don't have missunderstood the whole thing?

**Comment by 0x0ade** [comment]
From my understanding of Harmony, this looks good to me :)

**Pull request merged**
