### PR TITLE
Convert project to support multi-platform testing

### PR DESCRIPTION
**Pull request by hcoona**
The issue #21 shows AccessViolation on Windows platform because Windows protect memory page. This solution call `VirtualProtect` Windows API to rewrite the memory page protection level. Because we always write the code segment, we need to assign READ, WRITE, EXECUTION permissions to this memory page.

### CODE REVIEW

**Comment by hcoona** [comment]
I cannot get it passed on my compiler (VS2017) without the casting.

I made a platform checking before call the NativeLibrary, but not tested on Mono because of lacking Linux env.

**Comment by pardeike** [comment]
I use VS2017 too and it compiles fine - even without warnings. I assume that a cast should even throw on operands that cannot be casted to MethodBase. So I remain sceptical.

**Comment by hcoona** [comment]
Tried again and it works as you said. So I just removed it. Thanks :)

**Comment by hcoona** [comment]
I found Mono Docker container for testing on Linux, but I cannot get the test project compiled on Linux. Do you have any documents about it?

**Comment by hcoona** [comment]
I make a very basic test, it works on Linux with [Mono Docker container](https://docs.docker.com/samples/mono/)

**Comment by pardeike** [comment]
Sorry, for the delay. I was busy and I somehow missed that you tested it with linux mono. Can you quickly confirm that it works (no side effects) on Windows, Linux and Mac and also in .Net Core and mono?

Don't have the time to verify myself right now but would love to pull this.

**Comment by pardeike** [comment]
One more think: don't you think your protect call should be inside the WriteJump method? Can't see why someone might want to call the write without the unprotect.

**Comment by hcoona** [comment]
Your test project is broken somehow in my testing so I have to make a manual test which needs a lot of work. Would you mind if I just make a very simple test on all platform instead of full UTs?

I'll take a look into bring it into `WriteJump` method.

**Comment by pardeike** [comment]
Sure, that works for me. I am finally trying all the changes made to master myself on my dev machine (Win10) which means that I might be able to write full testing. I also have a MacBook to test on real hardware too.

May main focus still is to not break anything for the huge mono Rimworld community. I have a few bug fixes to the core logic to make: support for try/catch and a possible bug in the attributes for generic classes.

Thanks for your help

**Comment by hcoona** [comment]
I turned off 6 known failed unit test, converted the unit test project based on NUnit framework instead of MSTestV2. I add AppVeyor & Travis CI for automatically compiling & testing for Windows, Linux & Mac. All things goes well.

I suggest you login [AppVeyor](https://ci.appveyor.com/projects) & [Travis CI](https://travis-ci.org/) to enable CI for this project to prevent any breaks in the future.

**Comment by pardeike** [comment]
To be honest, I haven’t looked into CI for VS and github yet. So I need to figure out what this actually means for the project. Sorry for the delay, I would love to have CI in Harmony.

I’ll get back on this probably this weekend

**Comment by HoLLy-HaCKeR** [comment]
Any updates on this? I'm currently using @hcoona's branch in [a project of mine](https://github.com/HoLLy-HaCKeR/EazFixer/), but I would much prefer to use the original source.

**Comment by pardeike** [comment]
Yeah, I understand. To be honest, I am in the middle of preparing myself for the lifetime adventure of an Africa Rally in January but I promise you that I pick up and merge my current work with this request. Sorry for the inconvenience, I’ll keep you updated.

**Comment by HoLLy-HaCKeR** [comment]
Thanks a lot, and enjoy your rally! :)

**Comment by pardeike** [comment]
Hi again.

For me this pull is too much entangled with the change in dev/test environment. So I took the liberty to copy over the essential code to the current branch without the extra changes to testing etc.

I hope to get the full test suite working some day and as a reminder, I'll keep this pull request alive.

**Comment by pardeike** [comment]
I've converted the project to the latest VS2017 format. If you want you can help me update this pull request to match the change.

**Comment by hcoona** [comment]
@pardeike I solved the conflicts.

It should work on both Travis CI & AppVeyor now. You can try them after merging this PR.

**Comment by hcoona** [comment]
Wait, the Linux building is failing. I'll fix it soon.

**Comment by hcoona** [comment]
There are 3 tests still failing. I think you can fix them later.
* HarmonyTests.Patching.Transpiling.TestTranspilerException1
* HarmonyTests.StaticPatches.TestMethod1
* HarmonyTests.StaticPatches.TestMethod2

**Comment by pardeike** [comment]
I created an open source account at travis-ci.com and will make CI my priority now. Also, I think I can make travis trigger my docfx compilation which will automatically update the (currently sparse) documentation at harmony.pardeike.neta

As I haven’t done any CI in detail yet (and definitively not on a VS project) I hope someone can help me out here.

**Comment by pardeike** [comment]
Harmony now uses Azure Pipelines to automatically build documentation with docfx. Thanks for inspiring me to tackle this!

**Pull request merged**
