### PR TITLE
Porting Harmony to .NET Core 3

### PR DESCRIPTION
**Pull request by berkeleyinc**
Hey, 

I've been working on porting Harmony to .NET Core 3.
The main issue was that MethodInfo objects are not longer serializable in .NET Core

To bypass that, i've created a MethodInfoWrapper that traverses the RuntimeMethodInfo object and performs a shallow copy.
gg

### CODE REVIEW

**Comment by lbmaian** [comment]
Quick comment, not actually reviewing the code - just noticed the CI failed (when it's just been recently fixed) and looked into it:

You can't just remove the `net35`, `net45`, `net472`, `net48`, and (maybe) `netstandard2.1` target frameworks. Especially not when major users of Harmony include mods for games that still require the `net35` build like RimWorld.

If you have new code that requires `netcoreapp3.0`, delimit that code in a `#if NETCOREAPP3_0`/(`#else`)/`#endif` (replace `NETCOREAPP3_0` with `NETCOREAPP` if it works on all .NET Core versions).

**Comment by mitchcapper** [comment]
@berkeleyinc  thanks for this, works fantastic.

**Comment by lbmaian** [comment]
The CI failures indicate that the changes aren't compatible with .NET Framework 3.5, which doesn't support `dynamic`, nor has `System.Diagnostics.Contracts`.

And yes, there needs to be a package reference to Microsoft.CSharp but only for .NET Core builds.

So there's still cross-target-framework work to be done.

.NET Core specific code needs to be guarded with `#if NETCOREAPP`/`#endif`.

New package references (and any other additions to the .csproj) need to be guarded with `Condition="$(TargetFramework.StartsWith('netcoreapp'))"` attribute (or if it's really specific .NET Core 3.0, `Condition="'$(TargetFramework)' == 'netcoreapp3.0'"`).

**Comment by pardeike** [comment]
My latest changes to master make this PR obsolete. I also made sure that it's backwards compatible and that all tests success.

**Pull request closed without merging**
