### PR TITLE
Update patching-edgecases.md

### PR DESCRIPTION
**Pull request by podostro**
Added edge case "MissingMethodException: Attempted to access a missing method"

### CODE REVIEW

**Comment by pardeike** [comment]
After seeing this I wonder if this is too off topic for Harmony. If I would add all the cases similar to this one, the documentation would get bloated and not consumable anymore. 

As a compromise, I am open to add a new chapter called "Unity" or "Runtime Resolving Problems" to the documentation and we move your new section into that. 

What do you think?

**Comment by podostro** [comment]
I actually think this would be a basic guideline to using Harmony for Unity Games, since the intro makes it look like that is the purpose of the library. 
But if your focus is on patching anything and no longer explicitly Unity games; then I aggree, a new Unity focused section would be cleaner.

**Comment by pardeike** [comment]
Sorry for not getting back to you earlier. I think your motivation is good and the only thing I would like you to do is to move the code example out of the md file with a reference. Check out how the rest of the documenation is done.

Once that's fixed I pull this request.

**Comment by podostro** [comment]
The thing with motivations is, it dies... 
Also I'm currently too busy with my own work and not have time to contribute; so if you would be so kind as to do it yourself; or open request anyone else to do it. It would be great. 
Otherwise, time will tell when I'm able to do so.

**Comment by pardeike** [comment]
No worries. I just want to know your status. We all have stuff to do that gets in the way. Thanks for your contribution so far.

**Pull request merged**
